# Generated by Django 4.0.4 on 2022-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('images', models.ImageField(upload_to='')),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('public_price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
