# Generated by Django 4.0.4 on 2022-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(upload_to='photo/products'),
        ),
    ]
