# Generated by Django 4.0.4 on 2022-05-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_options'),
        ('store', '0002_alter_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.item')),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
            bases=('store.item',),
        ),
    ]
