# Generated by Django 4.0.4 on 2022-05-02 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilePhone', '0001_initial'),
        ('store', '0003_clothesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhoneItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.item')),
                ('chip', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('mobile_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilePhone.mobilephone')),
            ],
            bases=('store.item',),
        ),
    ]
