# Generated by Django 4.0.4 on 2022-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_mobilephoneitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephoneitem',
            name='internal_memory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
