# Generated by Django 4.0.4 on 2022-05-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sell_price',
        ),
    ]
