# Generated by Django 4.0.3 on 2022-05-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('customer', '0001_initial'),
        ('carts', '0003_remove_cartitem_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='CustomerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='OrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='PaymentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.payment'),
        ),
    ]
