# Generated by Django 4.0.4 on 2022-05-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='slug',
        ),
    ]
