# Generated by Django 4.0.4 on 2022-05-02 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mail', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('width', models.CharField(max_length=255)),
                ('import_price', models.FloatField()),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilePhone.design')),
                ('mobile_phone_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilePhone.mobilephonebrand')),
            ],
        ),
    ]
