# Generated by Django 4.0.3 on 2022-05-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fabric', models.CharField(max_length=255)),
                ('import_price', models.FloatField()),
                ('ShoeBrandID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoebrand')),
                ('ShoeCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoecategory')),
            ],
            options={
                'verbose_name': 'Shoes',
                'verbose_name_plural': 'Shoes',
            },
        ),
    ]
