# Generated by Django 4.0.4 on 2022-04-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('importPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.item')),
                ('version', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop')),
            ],
            bases=('store.item',),
        ),
        migrations.AddField(
            model_name='laptop',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.producer'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.type'),
        ),
    ]
