# Generated by Django 4.0.4 on 2022-04-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0006_laptop_producer_laptop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='importPrice',
            new_name='import_price',
        ),
    ]
