# Generated by Django 4.0.3 on 2022-05-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipfee', models.FloatField()),
                ('shipaddress', models.CharField(max_length=255)),
                ('shipphone', models.CharField(max_length=255)),
                ('shipname', models.CharField(max_length=255)),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField()),
                ('isOrder', models.BooleanField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment')),
                ('ShipmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shipment')),
            ],
        ),
    ]
